using UnityEngine;
using UnityEngine.UI;

namespace Cryville.Crtr.Browsing {
	internal class PathPart : MonoBehaviour {
		private int _id;
		private Text _exp;

#pragma warning disable IDE0051
		void Awake() {
			_exp = transform.Find("__text__").GetComponent<Text>();
		}
#pragma warning restore IDE0051

		internal void Load(int id, string exp) {
			_id = id;
			_exp.text = Parse(exp);
		}
		string Parse(string exp) {
			if (exp == "") return "(root)";
			else return exp;
		}
		public void OnClick() {
			GetComponentInParent<ResourceBrowser>().OnPathClicked(_id);
		}
	}
}